apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "study-scim.fullname" . }}
  labels:
    {{- include "study-scim.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "study-scim.postgresql.host" . | quote }}
  DB_PORT: "5432"
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  SCIM_BASE_URL: {{ .Values.app.scimBaseUrl | quote }}
