apiVersion: v1
kind: Secret
metadata:
  name: {{ include "study-scim.fullname" . }}
  labels:
    {{- include "study-scim.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-username: {{ .Values.postgresql.auth.username | quote }}
  db-password: {{ .Values.postgresql.auth.password | quote }}
  bearer-token: {{ .Values.app.bearerToken | quote }}
